export default {
  text: {
    color: 'lightgrey',
    size: 5.5,
    translateNumbers: false,
  },
  indicator: {
    size: 8,
    color: 'primary',
  },
  icon: {
    size: 7,
    color: 'lightgrey',
    type: 'ion',
  },
  button: {
    // height: 7,
    size: 7,
    color: 'white',
    bold: true,
    backgroundColor: 'primary',
    disabledColor: '#f3f4f5',
    disabledBackgroundColor: 'disabled',
  },
  image: {
    resizeMode: 'cover',
    progressColor: 'primary',
    errorColor: 'black',
    errorBackgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  inputError: {
    color: 'error',
    sizeScale: 0.7,
  },
  input: {
    size: 6.5,
    activeColor: 'primary',
    inactiveColor: '#D0D0D0',
    color: 'black',
    backgroundColor: 'white',
    placeholderColor: '#858F96',
    center: false,
    translateNumbers: true,
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderColor: 'primary',
    borderRadius: 20,
    borderWidth: 0.7,
    height: 7,
  },
  formInputFrame: {
    size: 5,
    placeholderColor: '#858F96',
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderColor: 'inputBorderColor',
    borderWidth: 1,
    borderRadius: 4,
    height: 8,
  },
  textArea: {
    size: 6.5,
    color: '#484848',
    backgroundColor: 'white',
    placeholderColor: '#858F96',
    height: 20,
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderColor: 'grey',
    borderWidth: 0.5,
    borderRadius: 4,
    translateNumbers: false,
    underlineColor: 'transparent',
  },
  picker: {
    size: 5,
    color: '#484848',
    backgroundColor: '#EEEEEE',
    placeholderColor: '#858F96',
    paddingVertical: 3,
    paddingHorizontal: 4,
    borderColor: '#EEEEEE',
    borderWidth: 1,
    borderRadius: 4,
    height: 8,
  },
  wheelPicker: {
    size: 5,
    color: '#484848',
    backgroundColor: 'white',
    paddingVertical: 4,
    borderRadius: 4,
    height: 7.5,
    placeholderColor: '#858F96',
    borderColor: 'inputBorderColor',
    borderWidth: 1,
  },
  datePicker: {
    size: 5,
    color: '#484848',
    backgroundColor: 'white',
    paddingVertical: 4,
    borderColor: 'inputBorderColor',
    borderWidth: 1,
    borderRadius: 4,
    height: 7.5,
    placeholderColor: '#858F96',
  },
  radioButton: {
    activeColor: '#007AF7',
    normalColor: 'grey',
    size: 5,
    labelColor: 'black',
    labelSize: 5,
  },
  checkBox: {
    activeColor: 'primary',
    normalColor: '#475673',
    size: 6,
    // elevation: 3,
    labelColor: '#475673',
    labelSize: 6.5,
    borderColor: '#475673',
    paddingLeft: 8,
  },
  toggleButtons: {
    activeBackgroundColor: 'primary',
    inActiveBackgroundColor: 'white',
    activeColor: 'white',
    inActiveColor: '#979797',
    activeBorderColor: 'primary',
    inActiveBorderColor: '#979797',
  },
  list: {
    indicatorColor: 'primary',
    errorLabelColor: 'error',
    noResultsLabelColor: 'black',
    retryButtonBackgroundColor: 'primary',
    retryButtoncolor: 'white',
  },
  tabBar: {
    height: 7,
    backgroundColor: 'white',
    activeTextColor: 'primary',
    activeTextSize: 5,
    activeTextBold: true,
    inactiveTextColor: '#B1B0B0',
    inactiveTextSize: 5,
    inactiveTextBold: false,
    underlineColor: 'primary',
    underlineHeight: 1,
  },
  tabBar2: {
    height: 10,
    backgroundColor: 'primary',
    activeTextColor: 'white',
    activeTextSize: 5,
    activeTextBold: true,
    inactiveTextColor: '#B1B0B0',
    inactiveTextSize: 5,
    inactiveTextBold: false,
    underlineColor: 'white',
    underlineHeight: 1,
  },
  swiper: {
    indicatorColor: 'rgba(255, 255, 255, 0.5)',
    indicatorActiveColor: 'rgba(255, 255, 255, 1)',
  },
  localNotifications: {
    info: {
      backgroundColor: '#333',
      closeColor: 'primary',
    },
    success: {
      backgroundColor: 'safe',
      closeColor: 'white',
    },
    error: {
      backgroundColor: 'error',
      closeColor: 'white',
    },
  },
};
